### ISSUE TITLE
Import : System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by slucky31** [slucky31/mycomicsmanager-api#103]
[12:16:11 INF] Request finished HTTP/1.1 POST http://192.168.1.25:5000/api/Comics application/json;+charset=utf-8 314 - 500 0 - 1090.7651ms 
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
[12:16:11 ERR] HTTP POST /api/Comics responded 500 in 1080.1025 ms 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadUInt32()
   at MyComicsManagerApi.Services.ComicService.Create(Comic comic) in /app/Services/ComicService.cs:line 65
   at SharpCompress.Common.Zip.StreamingZipHeaderFactory.ReadStreamHeader(Stream stream)+MoveNext()
   at SharpCompress.Readers.Zip.ZipReader.GetEntries(Stream stream)+MoveNext()
   at SharpCompress.Readers.AbstractReader`2.NextEntryForCurrentStream()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at SharpCompress.Readers.AbstractReader`2.MoveToNextEntry()
   at MyComicsManagerApi.Services.ComicFileService.ExtractImagesFromCbr(String comicEbookPath, String tempDir) in /app/Services/ComicFileService.cs:line 215
   at MyComicsManagerApi.Services.ComicFileService.ConvertComicFileToCbz(Comic comic) in /app/Services/ComicFileService.cs:line 135
   at MyComicsManagerApi.Controllers.ComicsController.Create(Comic comic) in /app/Controllers/ComicsController.cs:line 62
   at lambda_method1371(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
[12:16:11 ERR] Connection id "0HME3KRSRMLU3", Request id "0HME3KRSRMLU3:0000000D": An unhandled exception was thrown by the application. 
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by slucky31** [comment]
POur reproduire : Ghosted 04.cbr
