### ISSUE TITLE
Import : System.IO.InvalidDataException: End of Central Directory record could not be found.

### ISSUE THREAD

**Issue by slucky31** [slucky31/mycomicsmanager-api#104]
[12:30:30 INF] Route matched with {action = "Create", controller = "Comics"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.ActionResult`1[MyComicsManagerApi.Models.Comic] Create(MyComicsManagerApi.Models.Comic) on controller MyComicsManagerApi.Controllers.ComicsController (MyComicsManagerApi). 
[12:30:30 INF] Création du répertoire temporaire : /tmp/cjv5vhu3.kwr 
[12:30:30 INF] ExtractImagesFromCbz 
[12:30:31 INF] Executed action MyComicsManagerApi.Controllers.ComicsController.Create (MyComicsManagerApi) in 440.118ms 
[12:30:31 INF] Executed endpoint 'MyComicsManagerApi.Controllers.ComicsController.Create (MyComicsManagerApi)' 
[12:30:31 ERR] HTTP POST /api/Comics responded 500 in 449.7652 ms 
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at MyComicsManagerApi.Services.ComicFileService.ConvertComicFileToCbz(Comic comic) in /app/Services/ComicFileService.cs:line 125
   at MyComicsManagerApi.Services.ComicService.Create(Comic comic) in /app/Services/ComicService.cs:line 65
   at MyComicsManagerApi.Controllers.ComicsController.Create(Comic comic) in /app/Controllers/ComicsController.cs:line 62
   at lambda_method1371(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
[12:30:31 ERR] Connection id "0HME3KRSRMLU9", Request id "0HME3KRSRMLU9:00000002": An unhandled exception was thrown by the application. 
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at MyComicsManagerApi.Services.ComicFileService.ConvertComicFileToCbz(Comic comic) in /app/Services/ComicFileService.cs:line 125
   at MyComicsManagerApi.Services.ComicService.Create(Comic comic) in /app/Services/ComicService.cs:line 65
   at MyComicsManagerApi.Controllers.ComicsController.Create(Comic comic) in /app/Controllers/ComicsController.cs:line 62
   at lambda_method1371(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[12:30:31 INF] Request finished HTTP/1.1 POST http://192.168.1.25:5000/api/Comics application/json;+charset=utf-8 806 - 500 0 - 530.1862ms

**Comment by slucky31** [comment]
Pour reproduire : LEDroitdAuteur.cbz

**Comment by slucky31** [comment]
Vérfier le format du fichier !
C'est un rar en fait !!!!

**Comment by slucky31** [comment]
Utilisation de sharpcompress pour vérifier le type de fichier : https://github.com/adamhathcock/sharpcompress/blob/161f99bbad9e77115e25baab6dd2846c4f50d010/src/SharpCompress/Archives/ArchiveFactory.cs
