### ISSUE TITLE
Edit : ISBN Search

### ISSUE THREAD

**Issue by slucky31** [slucky31/mycomicsmanager-api#139]
2022-01-31 19:58:51 [ERR]  -- HTTP GET /api/books/getinfo/61f83a82825e6f9c98001e04 responded 500 in 6163.2559 ms
System.NullReferenceException: Object reference not set to an instance of an object.
   at MyComicsManagerApi.Services.BookService.SearchComicInfoAndUpdate(String isbn) in /app/Services/BookService.cs:line 82
   at lambda_method144(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2022-01-31 19:58:51 [ERR]  -- Connection id "0HMF4T3T0H0NA", Request id "0HMF4T3T0H0NA:00000005": An unhandled exception was thrown by the application.
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2022-01-31 19:58:51 [INF]  -- Request finished HTTP/1.1 GET http://192.168.1.25:5000/api/books/getinfo/61f83a82825e6f9c98001e04 - - - 500 0 - 6178.9003ms
2022-01-31 19:58:51 [INF]  -- Executed endpoint 'MyComicsManagerApi.Controllers.BooksController.SearchComicInfo (MyComicsManagerApi)'
2022-01-31 19:58:51 [INF]  -- Executed action MyComicsManagerApi.Controllers.BooksController.SearchComicInfo (MyComicsManagerApi) in 6156.1057ms
   at MyComicsManagerApi.DataParser.ComicHtmlDataParser.Parse(String isbn) in /app/DataParser/ComicHtmlDataParser.cs:line 46
   at MyComicsManagerApi.DataParser.BdphileComicHtmlDataParser.Search(String isbn) in /app/DataParser/BdphileComicHtmlDataParser.cs:line 230
MyComicsManagerApi.Exceptions.IsbnSearchNotFoundException: Aucun album trouvé pour l'isbn 61f83a82825e6f9c98001e04
2022-01-31 19:58:51 [WRN]  -- Aucune donnée n'a été remontée de la recherche !
2022-01-31 19:58:49 [INF]  -- Request finished HTTP/1.1 GET http://192.168.1.25:5000/api/comics/61f83a82825e6f9c98001e04 - - - 200 656 application/json;+charset=utf-8 44.4998ms
2022-01-31 19:58:49 [INF]  -- HTTP GET /api/comics/61f83a82825e6f9c98001e04 responded 200 in 43.7778 ms
2022-01-31 19:58:49 [INF]  -- Executed endpoint 'MyComicsManagerApi.Controllers.ComicsController.Get (MyComicsManagerApi)'
2022-01-31 19:58:49 [INF]  -- Executed action MyComicsManagerApi.Controllers.ComicsController.Get (MyComicsManagerApi) in 31.1342ms
2022-01-31 19:58:49 [INF]  -- Executing ObjectResult, writing value of type 'MyComicsManagerApi.Models.Comic'.

**Comment by slucky31** [comment]
https://www.bdphile.info/album/manga/2382-dragon-ball-38-le-sorcier-babidi
978-2-7234-2805-7
